name: yt-dl-server
version: 0.0.1
summary: Yet another YouTube-Dl Server
description: |
  Yet another YouTube-Dl Server

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  yt-dl-server:
    command: yt-dl-server
    plugs: [network, network-bind]
  youtube-dl:
    command: youtube-dl
    plugs: [network]

parts:
  youtube-dl:
    plugin: python
    python-packages:
      - youtube-dl
  yt-dl-server:
    plugin: nodejs
    source: .
